### ISSUE TITLE
coinstac-simulator performance problems

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#30]
I used [coinstac-simulator-load-tester](https://github.com/swashcap/coinstac-simulator-load-tester) to run a varying number of clients with a varying number of iterations:

![whoops-bad-labeling](https://cloud.githubusercontent.com/assets/1858316/18070799/3e70aa0a-6e05-11e6-9e48-4bdb36c2a444.png)

Each client computes the hash of a 1mb file on every iteration. The average client computation time is ~19.8ms. What’s concerning here is that simulating 20 clients each running 50 iterations takes 5 minutes and 48 seconds. Each client’s computation time is, on average, <1 second in this case. What’s taking up so much time?

**Comment by cdaringe** [comment]
as usual, my first guess is pouchdb server.  now that you clearly have some awesome benchmarking hooks setup, it would be cool to use [perf-now](https://www.npmjs.com/package/performance-now) to try and trace it.
- we could try measuring from clients getting a change event all the way to pipeline `run:end`
  - if this time is ~constant between iterations, we know the problem is not in our code, but rather in the network or pdbs
  - if these numbers do increase, we should probably profile the final saving of our docs in the pipeline runner.  this is _unlikely_.

i'm curious if we stretch out the polling interval to reduce the noise all of the clients induce on PDBS if that would increase perf too in the many client count scenarios.

easily the most troubling thing here is that none of these lines are flat.  something isn't able to keep up with steady state, right off the bat, seemingly no matter what.  we do expect _some_ increase in time on each iteration, because we are maintaining history on each client save, but I'd be hard pressed to think that such a factor would even be observable.

**Comment by cdaringe** [comment]
does the same happen against `couchdb`?

**Comment by swashcap** [comment]
Another test, this time on one of our servers:

![cstac-server-simulator](https://cloud.githubusercontent.com/assets/1858316/18135911/6207f0f0-6f58-11e6-9b90-888e3a377037.png)
- Server had 2 CPUs, 4GB rams
- 250 iterations w/ 5 clients took ~27 min
- Higher numbers of clients couldn’t complete higher numbers of iterations (probably due to errors?)
- Average client compute time for a single iteration was 55ms
- This only measures time spent within the computation. The entire run took >12 hours?

**Comment by swashcap** [comment]
@cdaringe Good ideas. We'll see how high a priority simulator is and check them out.

**Comment by zombieprocess** [comment]
**Adding some stat/graphs from VMware for context:**
![coinstac-disk-2day](https://cloud.githubusercontent.com/assets/8109526/18137567/15292e76-6f66-11e6-8d5c-bdf0436e3711.png)
![coinstac-network-2day](https://cloud.githubusercontent.com/assets/8109526/18137569/152bb218-6f66-11e6-842d-3d8dcd7009b9.png)
![coinstac-mem-2day](https://cloud.githubusercontent.com/assets/8109526/18137570/152f2998-6f66-11e6-9335-e29798c05e32.png)
![coinstac-cpu-2day](https://cloud.githubusercontent.com/assets/8109526/18137568/152a8776-6f66-11e6-86ac-1cbcda973f26.png)

**Comment by zombieprocess** [comment]
**Virtual Hardware:**
<img width="358" alt="VMware Hardware config" src="https://cloud.githubusercontent.com/assets/8109526/18137625/590f8c5c-6f66-11e6-930d-89a71064d463.png">

**CPU info:**

```
$ cat /proc/cpuinfo
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 26
model name  : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping    : 4
microcode   : 0x70d
cpu MHz     : 2000.000
cache size  : 15360 KB
physical id : 0
siblings    : 1
core id     : 0
cpu cores   : 1
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 11
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt hypervisor lahf_lm ida arat pln pts dtherm
bogomips    : 4000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```
