### ISSUE TITLE
Coinstac requires admin rights (at least on Linux) => use Sigularity instead of Docker?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [trendscenter/coinstac#554]
# Problem
Perhaps [Singularity](https://singularity.lbl.gov/) suits scientific pipelines more than Docker: no need to be an admin, _Coinstac_ doesn't have to run with admin rights. Doesn't sound good to run _Coinstac_ as admin, it may run external pipelines which are a security risk. Of course there are other security issues (such as sandboxing plugins) but the admin rights look like a security risk that could be avoided.

# Tasks

**Comment by everner-ds** [comment]
We have consider using Singularity, but it is not well supported on Windows and perhaps not on Mac anymore. In past versions, there were [instructions](https://singularity.lbl.gov/install-windows) for installing it on Windows using Vagrant, but this is quite complex. The [documentation for the current version](https://www.sylabs.io/guides/3.0/user-guide/quick_start.html) states that Linux system is required. Because we have committed to support both Mac and Windows, we cannot use Singularity at this time. If Singularity provides support for these operating systems, we may revisit this design choice in the future. Thanks.

**Comment by DimitriPapadopoulos** [comment]
I understand. Still I think security should a be a priority, before same delivery environment on all platforms.
