### ISSUE TITLE
DRNE Freesurfer has lambda parameter

### ISSUE THREAD

**Issue by everner-ds** [trendscenter/coinstac#617]
# Problem

The DRNE Freesurfer computation has lambda as a parameter in the computation set up. As lambda is a regularization parameter, and this computation does not do regularization, there should be no lambda parameter. Lambda is only for ridge regression.

# Tasks

Remove lambda from parameters that appear on computation set up.

**Comment by hvgazula** [comment]
@everner-ds  It's not a bug. It's okay to have lambda with normal equation as well. Just that in practice, since we deal with large datasets and normal equation (finding inverse) in not practical, we resort to gradient descent. For more info, please refer to the link below.

http://openclassroom.stanford.edu/MainFolder/DocumentPage.php?course=MachineLearning&doc=exercises/ex5/ex5.html

**Comment by everner-ds** [comment]
Okay, thanks. That makes sense. I'll close this issue.
