### ISSUE TITLE
Rethink Algorithm Development

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#65]
We should reconsider how algorithm authors will contribute to COINSTAC.

Currently, we require authors to write their computations in either JavaScript or use a JavaScript wrapper that points to their (largely Python) executable. We use stderr and stdout for communication, and require stdout be entirely JSON for successful computation processing. (stderr is used for logging, which, _wat_.) Our computation distribution system requires knowledge of git.

This proves problematic. Our interactions with authors indicates they have very little experience with JSON, and that they’re unwittingly writing malformed JSON to stdout (possibly logging from their executable). Furthermore, algorithm authors don’t seem to know or use version control.

We’ll fail if algorithm contribution is confusing or impossible for authors. We need to rethink this and address it.

**Comment by cdaringe** [comment]
it's probably worth asking a few qs:
- how many algo authors have we had?  are those (single digit # of humans) sufficiently large to qualify a sample?
- if an algo author is coding an algo, he or she should be _highly competent_ in programming in their language of choice.  otherwise, the integrity of the algo is at stake, and we have much bigger problems.  JSON dumping content should not be considered "too hard" for an algo author when they are competent to do advanced mathematics and general programming.  where should the technical threshold be??  i would subjectively lobby that run-of-the-mill programming serialization techniques should be an expectation of algo authors. 

stdout/stderr behavior, also, IMHO, was reasonable given negative 0 time to crank out a feature. we collectively was discussed to use file i/o, which we never got around to implementing.  writing a file IMHO is often more difficult than a `print(...)` statement :).  now ur talkin' streams _and_ some serialization mechanism.
